### ISSUE TITLE
Snow + Hill

### ISSUE THREAD

**Issue by SomeTroglodyte** [ravignir/5Hex-Tileset#1]
You'll surely know Unciv now layers well and has hills as feature instead of baseterrain so you could benefit + redesign a few tiles...
Even so, the new hills on snow have more problems with 5Hex (read on after the screenshots):
#### 5Hex
![image](https://user-images.githubusercontent.com/63000004/117358906-fbfee900-aeb6-11eb-8e92-5751f10822bb.png)
#### FantasyHex
![image](https://user-images.githubusercontent.com/63000004/117358957-120ca980-aeb7-11eb-8f97-e8671c0a275e.png)

Fix:
Bulk rename `I`to `i` for the Snow png's
```json
		"Snow+Hill": ["Snow","Hill"],
		"Snow+Hill+Coal": ["Snow","Hill","Coal"],
```
![image](https://user-images.githubusercontent.com/63000004/117359898-59476a00-aeb8-11eb-9b54-b07a8299168a.png)

Lastly: :+1: :+1: :+1: :+1: :+1: - significantly enhances the fun! What an admirable pile of work!

**Comment by ravignir** [comment]
This repository still uses old tile layering - so it kinda does work with new unciv versions, but not perfectly. Anyway good catch with the Snow+HIll name, but it does not really matter. There is a new repository that's is the most updated one and fully utilizes new layering and Hills being a feature: https://github.com/ravignir/5HexPlus - you should use it instead. This repository will be soon fully replaced with the new content - but maybe i should do it now?.

**Comment by SomeTroglodyte** [comment]
Oh, new repo instead of new branch... OK, why not - or does it count players will see an update to the existing mod directly in the mod manager screen? Not that it stands out much, but it's coded. However you choose, keep up the good work!

**Comment by SomeTroglodyte** [comment]
Yes, 5Hex Plus works fine. But I'd ditch the repo and use the old one for one reason alone: It still appears on the first page while for Plus you need to scroll down all the way after clicking next page once. Also, the description text has more room, perhaps to hint it needs an extra step as 'permament visual mod'...

Btw, the mod manager neither passes any sorting parameter in the github query (if they even exist) nor does it sort github's response. So it's probably ordered by some internal SQL IDENTITY column - first come first serve?

**Comment by ravignir** [comment]
ok i've copied other repository contents here, and deleted all of the old, redundant sprites. I am open for suggestions which tiles I should redesign :)

**Comment by SomeTroglodyte** [comment]
Redesign graphics? Dunno whether I haven an eye for that. But if I come across any I'll be sure to tell you. Am thinking more about the mod manager screen code... I saw that you were busy right within Unciv even before the comment mail arrived, so that part was confirmed working :grin:
