### ISSUE TITLE
Lumber Mill not showed

### ISSUE THREAD

**Issue by AdityaMH** [ravignir/5Hex-Tileset#2]
I think don't need description.
![IMG_20210521_011417](https://user-images.githubusercontent.com/33791472/119028637-e7037900-b9d1-11eb-9855-cc1cdc676670.jpg)

**Comment by AdityaMH** [comment]
But, me after updated mod. This bug still happen.

**Comment by ravignir** [comment]
Hmm, looks like Plains and Grasslands are the only tiles that have this issue. This must be connected to unciv code, and i can't fix it with a json.

**Comment by AdityaMH** [comment]
@SomeTroglodyte , @yairm210
Can you solve this?

**Comment by ravignir** [comment]
i can solve it with 2 new sprites, but the thing i that's not a real solution to a problem.

**Comment by SomeTroglodyte** [comment]
Uh, from stepping `getTileBaseImageLocationsNew` you can either have a json entry for "Plains+Hill+Forest+Lumber mill" or an image named like that or 4 separate images, no mixing rules... and in my FantasyHex "Lumber mill.png" is missing. Strange the code actually returns TileSets/_FantasyHex_/Tiles/Lumber mill at that point when I have 5Hex perma'ed... Maybe that's replaced later.

**Comment by ravignir** [comment]
"Plains+Hill+Forest+Lumber mill" does work. Any tile combination with Hills does. "Tundra+Forest+Lumber mill" also works. The only tiles that do not work are "Grassland+Forest+Lumber mill" and "Plains+Forest+Lumber mill", but i am completely clueless why, given there are no issues with Tundra tile.

**Comment by SomeTroglodyte** [comment]
To be clearer: Priority is
1. Look into ruleVariants for _complete_ list , in this case "Plains+Hill+Forest+Lumber mill". If found, follow it. Else:
2. Look for an image with that same name. If it exists, use it. In this case "TileSets/FantasyHex/Tiles/Plains+Hill+Forest+Lumber mill" Else:
3. Piece the thing together from discrete images, one by one. One Image Plains, one Hill, one Forest, one Lumber Mill.

<details><summary>This replacement with a jota more flexibility:</summary>

```kotlin
    fun getTileBaseImageLocationsNew(viewingCiv: CivilizationInfo?): List<String> {
        if (viewingCiv == null && !showEntireMap) return listOf(tileSetStrings.hexagon)
        if (tileInfo.naturalWonder != null) return listOf(tileSetStrings.getTile(tileInfo.naturalWonder!!))

        val shouldShowImprovement = tileInfo.improvement != null && UncivGame.Current.settings.showPixelImprovements

        val shouldShowResource = UncivGame.Current.settings.showPixelImprovements && tileInfo.resource != null &&
                (showEntireMap || viewingCiv == null || tileInfo.hasViewableResource(viewingCiv))

        var resourceAndImprovementSequence = sequenceOf<String?>()
        if (shouldShowResource) resourceAndImprovementSequence += sequenceOf(tileInfo.resource)
        if (shouldShowImprovement) resourceAndImprovementSequence += sequenceOf(tileInfo.improvement)
        resourceAndImprovementSequence = resourceAndImprovementSequence.filterNotNull()

        val terrainImages = (sequenceOf(tileInfo.baseTerrain) + tileInfo.terrainFeatures.asSequence()).filterNotNull()
        val allTogether = (terrainImages + resourceAndImprovementSequence).joinToString("+")
        val allTogetherLocation = tileSetStrings.getTile(allTogether)
        val terrainLocation = tileSetStrings.getTile(terrainImages.joinToString("+"))
        val resourceAndImprovementLocation = tileSetStrings.getTile(resourceAndImprovementSequence.joinToString("+"))

        return when {
            tileSetStrings.tileSetConfig.ruleVariants[allTogether] != null -> tileSetStrings.tileSetConfig.ruleVariants[allTogether]!!.map { tileSetStrings.getTile(it) }
            ImageGetter.imageExists(allTogetherLocation) -> listOf(allTogetherLocation)
            ImageGetter.imageExists(terrainLocation) && ImageGetter.imageExists(resourceAndImprovementLocation) -> listOf(terrainLocation, resourceAndImprovementLocation)
            else -> getTerrainImageLocations(terrainImages) + getImprovementAndResourceImages(resourceAndImprovementSequence)
        }
    }
```
</details>

... wouldn't help because it only additionally looks for "TileSets/FantasyHex/Tiles/Plains+Hill+Forest" plus "TileSets/FantasyHex/Tiles/Lumber mill"...

**Comment by SomeTroglodyte** [comment]
Tundra+Hill+Forest+Lumber mill works and Plains doesn't because the 4-part image is there and the other 4-part isn't.

**Comment by SomeTroglodyte** [comment]
Or, top-down instead of bottom-up, do one nice little "Lumber mill.png" with as much transparency as possible and look how far that gets you.

Idea - should I cheat a map having all possible combinations, including those forbidden by rules but not by class structure?

**Comment by SomeTroglodyte** [comment]
> "Plains+Hill+Forest+Lumber mill" does work. Any tile combination with Hills does. "Tundra+Forest+Lumber mill" also works. The only tiles that do not work are "Grassland+Forest+Lumber mill" and "Plains+Forest+Lumber mill", but i am completely clueless why, given there are no issues with Tundra tile.

Oh - I tested with Plains+Hill+Forest+Lumber mill only because Plains+Forest+Lumber mill looked OK...? Then again I haven't updated 5Hex for a few days. 

Still, observations on how `getTileBaseImageLocationsNew` ticks should still explain every single result. Except if code I haven't seen sometimes calls _another_ tile look resolving helper... But I don't think so. Then again, I haven't looked into the commit diffs, I've only set a conditional breakpoint in TileGroup for my tile's coords...

**Comment by ravignir** [comment]
```
"Plains+Forest+Lumber mill": ["Plains","Forest+Lumber mill"]
"Grassland+Forest+Lumber mil": ["Grassland","Forest+Lumber mill"]
"Tundra+Forest+Lumber mill": ["Tundra","TF+Lumber mill"]
	    	
"Plains+Hill+Forest+Lumber mill": ["Plains","Hill","HF+Lumber mill"]
"Grassland+Hill+Forest+Lumber mill": ["Grassland","Hill","HF+Lumber mill"]
"Tundra+Hill+Forest+Lumber mill": ["Tundra","Hill","HF+Lumber mill"]
```
![Screenshot_20210521-183935(1)](https://user-images.githubusercontent.com/30041793/119171084-65a8f680-ba64-11eb-9a7a-d8c538c3acdc.png)
Makes completely no sense imo. All Hill types are ok, all of tundra is ok, only these bare plains and bare grassland tiles aren't.

**Comment by ravignir** [comment]
Looks to be working after I've added "Plains+Forest" and "Grassland+Forest" to tileset.json 
Apparently they are not redundant.

**Comment by SomeTroglodyte** [comment]
>Looks to be working after I've added "Plains+Forest" and "Grassland+Forest" to tileset.json

Should be possible to have it layer Forest onto Plains and Grassland separately, but then it would be the same forest and looks would depend on transparency.

Another thing: ModManager will _not_ delete _any_ files on updating a mod! A fix is somewhere deep in my stashes... Meanwhile, everybody should delete mod first then reinstall...

**Comment by SomeTroglodyte** [comment]
![image](https://user-images.githubusercontent.com/63000004/119174351-c3d7d880-ba68-11eb-9b98-42df8e9ea73e.png)
I must be doing something wrong myself - that's not even adding lumber mills...

**Comment by ravignir** [comment]
Btw, that looks like heavily outdated version of 5Hex.

**Comment by SomeTroglodyte** [comment]
Freshly deleted + downloaded using the mod manager an hour ago?

**Comment by ravignir** [comment]
Weird. It kind of looks like if it was not reading tileset.json and the grasland+hill+forest tile looks like in the old version. I remember having some similar issues where the game used 5Hex even tho i did not have it in mods folders  as it was a freshly compiled jar.

**Comment by SomeTroglodyte** [comment]
I'm not worried - I hope the little code analysis helped.
