### ISSUE TITLE
Mod currently not initializing

### ISSUE THREAD

**Issue by Zoogzin** [ravignir/5Hex-Tileset#4]
Here is a list of the mods i have installed. I have tried creating new games with every combination of the mods off or on, the tileset no longer loads. Trying to load old save files which used to work doesnt help either. All of the three mods were updated at once.

![Screenshot_20211104-221651_UnCiv](https://user-images.githubusercontent.com/93752076/140452699-e297687e-dfad-45c7-84e5-d3c2ca1eff32.jpg)
![Screenshot_20211104-222204_UnCiv](https://user-images.githubusercontent.com/93752076/140453074-30526121-d6a2-4d9e-b97c-94d971301736.jpg)
![Screenshot_20211104-222256_UnCiv](https://user-images.githubusercontent.com/93752076/140453155-c7525245-999b-4bb7-a781-07121e87b864.jpg)

**Comment by ravignir** [comment]
But i see you have permanent audiovisual mod disabled.

**Comment by Zoogzin** [comment]
I dont recall ever needing that setting checked, but i turned it on per your instructions and it still isn't working. As far as hardware, I've got a galaxy s20 fe.

**Comment by ravignir** [comment]
> 
> 
> I dont recall ever needing that setting checked, but i turned it on per your instructions and it still isn't working. As far as hardware, I've got a galaxy s20 fe.

you also need to switch to 5hex tileset in options.

**Comment by Zoogzin** [comment]
It shows up now, thank you!
